# Numpy

### In Python, Numpy is a package which contain variable, functions, classes and large library of methematic function to work with scientific calculations. 
#### Numpy can be used to create 'n' dimentional Arrays where 'n' is any integer. We can create 1-Dimentional Array, 2-D Array, 3-D Array and so on....

#### Numpy's Array class is called 'nd-array'. It is also know as 'alias' name array. There is anpther class array in Pythone which is different from Numpy's Array class.....


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        # Import Numpy
    There are two way to import Numpy:
    1. import numpy
                   -This will import the entire numpy module.
    2. from numpy import*
                   -This will import all variables, classes, objects etc from numpy package
                   -Here * means All

# One Dimentional Array- Single Row, Multiple Colums

### Ways of Creating Array in Numpya
    array () Function
    linspace () Function
    logspace () Function
    arange () Function
    zeros () Function
    ones () Function


## array () function
    array() function of numpy is used to create an array.
### Syntax:
####    numpy.array(object, dtype=none, copy=True, order='K', subok=False, ndmin=0)

#### from numpy import*
#### array_name = numpy.array([elements])
    Ex by using method-1:-
    import numpy
    stu_roll = numpy.array([10,20,30,40,50])
    stu_roll = numpy.array([10,20,30,40,50], int)               #int is dtype
    stu_roll = numpy.array([10.1,20.5,30.7,40.2,50.3], float)   #float is dtype
    stu_roll = numpy.array(['s','b','c','d'])               
    stu_name = numpy.array(['Nasir','Ali','Yasir'], str)        #str is dtype             
    
    
    Ex by using method-2:- In this method, we don't need to use use 'numpy ' in our variables
                           So, This method is much more easy as compare to method-1
    from numpy import *
    stu_roll = array([10,20,30,40,50])
    stu_roll = array([10,20,30,40,50], int)               #int is dtype
    stu_roll = array([10.1,20.5,30.7,40.2,50.3], float)   #float is dtype
    stu_roll = array(['s','b','c','d'])               
    stu_name = array(['Nasir','Ali','Yasir'], str)        #str is dtype             
    
    
    
    
    
     

In [26]:
#Index: An index represent the position number of an array's elements
# Ex:- number of index always be 1 point less than number of element becuase index alway started from 0 by defaul in pytho
    
from numpy import*
stu_roll = array([10,20,30,40,50])
print(stu_roll[0])         # stu_roll = 10
print(stu_roll[1])         # stu_roll = 20
print(stu_roll[2])         # stu_roll = 30
print(stu_roll[3])         # stu_roll = 40
print(stu_roll[4])         # stu_roll = 50
print("Given Array:", stu_roll)
print ("Type of given Array:",type(stu_roll))
print(" ")

# we can also modidy an array

stu_roll[0]= 15
print ("After modifying the first element of given array is ",stu_roll[0])
print ("The given array datatype is ", stu_roll.dtype)

10
20
30
40
50
Given Array: [10 20 30 40 50]
Type of given Array: <class 'numpy.ndarray'>
 
After modifying the first element of given array is  15
The given array datatype is  int32


In [ ]:
#we can also sotre chracters in an array
from numpy import*
stu_roll = array(['a','b','c','d'])
print(stu_roll[0])         # stu_roll = a
print(stu_roll[1])         # stu_roll = b
print(stu_roll[2])         # stu_roll = c
print(stu_roll[3])         # stu_roll = d
print(stu_roll[4])         # stu_roll = error because it is out of bound


In [35]:
# we can also store string in an array
#we can also sotre chracters in an array
from numpy import*
stu_name = array(['Nasie','Yasir','Adil','Ali'])
print(stu_name[0])         # stu_roll = a
print(stu_name[1])         # stu_roll = b
print(stu_name[2])         # stu_roll = c
print(stu_name[3])         # stu_roll = d
print(stu_name.dtype)      # U5 means that the maximum chracter in a given array is 5

Nasie
Yasir
Adil
Ali
<U5


### Accessing Array Using for-loop
#### Syntax:
    from numpy import*
    array_name = array(['a','b','c','d'])
    
##### Without Index
    for element in array_name:
        print (element)
        
##### With Index
    n = len(array_name)          # len() funcion tell the number of elements not index number
    for i in range(n):           # range() function tell the index number
       print (array_name[i])
        

In [45]:
# without index number
from numpy import*
stu_roll = array ([10,20,30,40,50])

for element in stu_roll:             # element is a variable in which number of elements can be store
    print (element)

10
20
30
40
50


In [51]:
# with index number
from numpy import*
stu_roll = array ([10,20,30])

n = len(stu_roll)             # it tells, how many number elements that will assign in 'n' which will be 3

for i in range(n):            # i can be chnage because it's variable name,and range function will assign the index numbers
    print ("index", i, "=", stu_roll[i])


index 0 = 10
index 1 = 20
index 2 = 30


### Accessing Array Using while-loop
#### Syntax:
#### Without Index
    from numpy import*
    array_name = array(['a','b','c'])
    
    n = len(array_name)
    
    i=0
    while i<n:
        print (array_name[i])
        i += 1
#### With Index
    from numpy import*
    array_name = array(['a','b','c'])
    
    n = len(array_name)
    
    i=0
    while i<n:
        print (i, array_name[i])
        i += 1


In [52]:
#without index num
from numpy import*
stu_roll = array ([10,20,30])

n = len(stu_roll)         # it tells, the number of elements in a given an array

i = 0         # for while-loop, we need to assign a variable 
while i<n:
    print (stu_roll[i])
    i+=1

10
20
30


# linspace () function
     linspace () Function is use to create an array with even spaced numbers between starting point and stop point
### Syntax:
#### numpy.linspace(start, stop, num=50, endpoint=True, retstep=False, dtyp= None, axix=0)
    where:
         start - It represents starting point
         stop  - It represents ending point
         num   - It represents the number of parts the element should be divided. By default is 50, 
                 it must be non-negative.
         endponit - if True,then the stop point is the last element. 
                    if False, then the stop point is not included
 
 
 ### Creating Array Using linspace () Function:
 ### Syntax:
    from numpy import*
    array_name = linspace (start, stop, num=50, endpoint=True) 
                           # endpoint will be 'True' by default, it does not meter if you write or not
              
    Ex:-
    from numpy import *
    a = linspace (1,8)           # num=50, by defual it will will divide the number between 1 to 8                                       in 50 parts becuase it takes 50 by-default
    a = linspace (1,8,num=5)     # num=5, in this case it will divide the number between 1 to 8
    a = linspace (1,8,5)           in 5 parts because we mentioned in it's linspace () function.
    
    a = linspace (1,8,5, endpoint=False) # If we mention endpoint is False then it will not include                                               the last digit like in this it will not considet the                                                    number 8....
    
    
    Note: we can access using for-loop and while-loop

### Accessing linspace () fucntion

In [111]:
from numpy import*
a = linspace (1,10,5)
print (a)

#we can also call its index number
print (" ")
print (a[0])
print (a[1])
print (a[2])
print (a[3])
print (a[4])

print (" ")

# by-default division between two numbers
from numpy import*
b = linspace (1,10)
print (b)

print (" ")

# what  if we use endpoint is false???
from numpy import*
c = linspace (1,10, 5, endpoint=False)
print (c)

[ 1.    3.25  5.5   7.75 10.  ]
 
1.0
3.25
5.5
7.75
10.0
 
[ 1.          1.18367347  1.36734694  1.55102041  1.73469388  1.91836735
  2.10204082  2.28571429  2.46938776  2.65306122  2.83673469  3.02040816
  3.20408163  3.3877551   3.57142857  3.75510204  3.93877551  4.12244898
  4.30612245  4.48979592  4.67346939  4.85714286  5.04081633  5.2244898
  5.40816327  5.59183673  5.7755102   5.95918367  6.14285714  6.32653061
  6.51020408  6.69387755  6.87755102  7.06122449  7.24489796  7.42857143
  7.6122449   7.79591837  7.97959184  8.16326531  8.34693878  8.53061224
  8.71428571  8.89795918  9.08163265  9.26530612  9.44897959  9.63265306
  9.81632653 10.        ]
 
[1.  2.8 4.6 6.4 8.2]


### Accessing linspace () fucntion using for-loop & while-loop


In [108]:
#using for-loop
from numpy import*
a = linspace (1,8,5)

#Without Index:
for elements in a:
    print (elements)
    
print (" ")

#With Index
n = len(a)
for i in range(n):
    print("index", i, "=", a[i])
    
    
print (" ")

#using while loop
x = 0
while x<n:
    print (a[x])
    x+=1


1.0
2.75
4.5
6.25
8.0
 
index 0 = 1.0
index 1 = 2.75
index 2 = 4.5
index 3 = 6.25
index 4 = 8.0
 
1.0
2.75
4.5
6.25
8.0


# logspace () function
     logspace () function is used to create an array with evenly spaced numbers logarithmically. 
     The sequence at base ** start(base to the poswer of start) and ends iwth base** stop.
        
### Syntax:
#### numpy.logspace(start, stop, num=50, endpoint=True, base=10.0, dtyp= None, axix=0)
    where: 
         start - It represents starting element which will become base 
                 to the power of start(base^ start)
         stop  - It represents starting element which will become base 
                 to the power of stop(base^ stop)
         num   - It represents the number of parts the element should be divided. By default is 50, 
                 it must be non-negative.
         endponit - if True,then the stop point is the last element. 
                    if False, then the stop point is not included
         base  - The base of the log space.
         dtype - The type of an array
 
 ### Creating Array Using logspace () Function:
 ### Syntax:
     from numpy import*
     array_name = logpace numpy.logspace(start, stop, num=50, endpoint=True, base=10.0, dtyp= None,                                            axix=0)
     
     Ex:
     from numpy import*
     a = logspace(1,3)         # by default it will divide into 50 parts
     a = arrange(1,3,5)        # it will divide into 5 parts
     

### Accessing logspace () function


In [105]:
from numpy import*
a = logspace (1,3,5)     # by default the base = 10.0
print (a)

print(" ")

b = logspace (1,3,5, base=12.0)         # by user requirement, we can create specific base
print(b)


[  10.           31.6227766   100.          316.22776602 1000.        ]
 
[  12.           41.56921938  144.          498.83063258 1728.        ]


### Accessing logspace () function using for-loop & while-loop

In [106]:
# using for-loop
from numpy import*
a = logspace (1,3,5)

#Without Index:
for elements in a:
    print (elements)
    
print (" ")

#With Index
n = len(a)
for i in range(n):
    print("index", i, "=", a[i])
    
    
print (" ")

#using while loop
x = 0
while x<n:
    print (a[x])
    x+=1

10.0
31.622776601683793
100.0
316.22776601683796
1000.0
 
index 0 = 10.0
index 1 = 31.622776601683793
index 2 = 100.0
index 3 = 316.22776601683796
index 4 = 1000.0
 
10.0
31.622776601683793
100.0
316.22776601683796
1000.0


# arange () function
     a-range () function is used to create an array with a group of elements from start to one element prior to stop in steps of stepsize.
    
### Syntax:
#### numpy.arange(start, stop,stepsize, dtyp= None)
    where:
         start - It represents starting point, the default start value is 0.
         stop  - It represents ending point, the intervarl does not include this value, 
                 except in some cases where step is not an integer and floating point 
                 round-off affects the length of out.
        
      stepsize - Spacing between values. The default stepzise is 1.
 
 
 ### Creating Array Using arange () Function:
 ### Syntax:
     from numpy import*
     array_name = arrange (start,stop,stepsize,dtype=None)
     
     Ex:
     from numpy import*
     a = arange(5)
     a = arrange(0,5,1)        #starting point is 0, ending point is 5 but 5 will not include,                                          stepsize is 1
     

### Accessing arange () function

In [88]:
from numpy import*
a = arange (5)     # 5 will not include
print (a)

b = arange (0,5)
print(b)

c = arange (0,5,1)
print (c)

[0 1 2 3 4]
[0 1 2 3 4]
[0 1 2 3 4]


### Accessing arange () function using for-loop & while-loop

In [95]:
#using for-loop
from numpy import*
a = arange (1,5,1)

#Without Index:
for elements in a:
    print (elements)
    
print (" ")

#With Index
n = len(a)
for i in range(n):
    print("index", i, "=", a[i])
    
    
print (" ")

#using while loop
x = 0
while x<n:
    print (a[x])
    x+=1


1
2
3
4
 
index 0 = 1
index 1 = 2
index 2 = 3
index 3 = 4
 
1
2
3
4


# zeros () function
     zeros () Function is used to create an array with all zeros elements.
### Syntax:
#### numpy.zeros (shape, dtype=float, order = 'C')
    where:
         shape - It represents the shape of new array, It can be an int which will represent the                        number of elements or can be tuple of int. ex:- 5, (5,),(5,1)
         dtype - The desired data-type for the array.
         order - Wheter to store multi-dimensional data in row-major(C-Style) or 
                 column-major (Fortan-style) order in memeory. It can be C or F
 
 ### Creating Array Using zeros () Function:
 ### Syntax:
     from numpy import*
     array_name = numpy.zeros (shape, dtype=float)
     
     Ex:
     from numpy import*
     a = zeros (5)
     a = arrange(5,dtype=int) 

### Accessing zeros () function

In [97]:
from numpy import*
a = zeros (5)     # there will be 5 zeros in a single row
print (a)

b = zeros (5, dtype=int)
print(b)

c = zeros (5,dtype= float)
print (c)

[0. 0. 0. 0. 0.]
[0 0 0 0 0]
[0. 0. 0. 0. 0.]


### Accessing zeros () function using for-loop & while-loop

In [98]:
#using for-loop
from numpy import*
a = zeros (5, dtype=int)

#Without Index:
for elements in a:
    print (elements)
    
print (" ")

#With Index
n = len(a)
for i in range(n):
    print("index", i, "=", a[i])
    
    
print (" ")

#using while loop
x = 0
while x<n:
    print (a[x])
    x+=1


0
0
0
0
0
 
index 0 = 0
index 1 = 0
index 2 = 0
index 3 = 0
index 4 = 0
 
0
0
0
0
0


# ones () function
     zeros () Function is used to create an array with all 1s elements.
### Syntax:
#### numpy.ones (shape, dtype=float, order = 'C')
    where:
         shape - It represents the shape of new array, It can be an int which will represent the                        number of elements or can be tuple of int. ex:- 5, (5,),(5,1)
         dtype - The desired data-type for the array.
         order - Wheter to store multi-dimensional data in row-major(C-Style) or 
                 column-major (Fortan-style) order in memeory. It can be C or F
 
 ### Creating Array Using ones () Function:
 ### Syntax:
     from numpy import*
     array_name = numpy.ones (shape, dtype=float)
     
     Ex:
     from numpy import*
     a = ones (5)
     a = ones(5,dtype=int) 

### Accessing ones () function

In [100]:
from numpy import*
a = ones (5)     # there will be 5 zeros in a single row
print (a)

b = ones (5, dtype=int)
print(b)

c = ones (5,dtype= float)
print (c)

[1. 1. 1. 1. 1.]
[1 1 1 1 1]
[1. 1. 1. 1. 1.]


### Accessing ones () function using for-loop & while-loop

In [101]:
#using for-loop
from numpy import*
a = ones (5, dtype=int)

#Without Index:
for elements in a:
    print (elements)
    
print (" ")

#With Index
n = len(a)
for i in range(n):
    print("index", i, "=", a[i])
    
    
print (" ")

#using while loop
x = 0
while x<n:
    print (a[x])
    x+=1


1
1
1
1
1
 
index 0 = 1
index 1 = 1
index 2 = 1
index 3 = 1
index 4 = 1
 
1
1
1
1
1


# Mathemetical Operations on Arrays Using Numpy

In [112]:
from numpy import*
a = array([5,10,15,20,25])
a = a + 5  # similarly, we can subtract, multiply or divide two array using arithmetic operators
print (a)

[10 15 20 25 30]


In [115]:
from numpy import*
a = array([5,10,15,20,25])
a = a + 5  # similarly, we can subtract, multiply or divide two array using arithmetic operators

for element in a:
    print (element)

10
15
20
25
30


In [116]:
from numpy import*
a = array([5,10,15,20,25])
b = array([5,10,15,20,25])
c = a + b  # similarly, we can subtract, multiply or divide two array using arithmetic operators
print (c)

[10 20 30 40 50]


In [118]:
from numpy import*
a = array([5,10,15,20,25])
b = array([5,10,15,20,25])
c = a + c

for el in c:
    print (el)

20
40
60
80
100


# Comparison Operations on Arrays Using Numpy
    Comparison operators can be used to compare arrays. 
    The size of an array must be same.
    Comparison operators compares the corresponding elements of teh array 
    and returns another array with Boolen value. 
 
### any() function & all() function
#### any() function: This function reutrns 'True', if anyone elements of the iterable is True. If iterable is empty then returns 'False'.

#### all() function: This function reutrns 'True', if all elements of the iterable are True or iterable is empty/


In [121]:
from numpy import*
a = array([5,10,15,20,25])
b = array([5,12,15,20,50])   # size of a and b must be samce

c= a==b                     # similarly, we can perform other copmarios like <,>,<=,>= etc.
print (c)

[ True False  True  True False]


In [125]:
#any () function 
from numpy import*
a = array([5,10,15,20,25])
b = array([5,12,15,30,25])  # if anylements are same in given two array then it will print the 'True'

c = a==b
any(c)

True

In [126]:
#all () function 
from numpy import*
a = array([5,10,15,20,25])
b = array([5,12,15,30,25])   # if all elements are same then it will print the 'True'
 
c = a==b
any(c)

True

### where () Funtion:
#### This function is used to create a new array which contain, returned element chosen from expression 1 or expression 2 depending on condition.
#### If condition is Ture, then the epxression 1 will be executed elese expression 2 will be executed. 

### Syntax:
#### numpy.where(condition, expression1, epxression2)

    Ex:
       a = array([1,2,3,4,5,6,7])
       b = array([0,1,2,3,4,5,6])
       c = where (a>b, a, b)

In [131]:
from numpy import*
a = array([1,2,3,4,5,6,7])
b = array([0,1,2,3,4,5,6])
result = where (a<b, a, b)   # if the condition is true, then a-part will execute otherwise b-part will execure
print (result)

[0 1 2 3 4 5 6]


### where () Funtion:
#### This function is used to determine the position of elements which are non-zero.
#### This function returns an array that contains the indexes of the element of the array which are not equal to zero.
### Syntax:
#### numpy.nozero(array_name)

    Ex:
       a = array([1,2,3,4,5,6,7])
       c = nonzero (a)

In [133]:
from numpy import*
a = array([0, 1,2, 0 ,3,4,5, 0, 6,7])
result = nonzero(a)
print (result)

(array([1, 2, 4, 5, 6, 8, 9], dtype=int64),)


## Aliasing Array
#### Aliasing means giving another name to the existing object. It does not mean copying.

    Ex:
    a = array([1,2,3,4,5,6,7])
    b = a                      # it does not mean both are same, it is use to give another name 
   

In [135]:
from numpy import*
a = array([1,2,3,4,5,6,7])
b = a                      

print (a)
print (b)
print ("a", id(a))
print ("b", id(b))   # both addresses are same,just giving another name 

[1 2 3 4 5 6 7]
[1 2 3 4 5 6 7]
a 2970128129680
b 2970128129680


## view() Method
#### This method is used to construct a new view of array with the same data of existing array. 
#### The existing array and new array will share different memory locations.
#### If the new array get modified. the esisting will also be modified as the element in both the array  will be like mirror image.

    Ex:
    a = array([1,2,3,4,5,6,7])
    b = a,view()                      # data will be same but memory location will be different
                                    # modified data will also share in both array 
   

In [145]:
from numpy import*
a = array([1,2,3,4,5,6,7])
b = a.view()
print (a)
print (b)
print ("a", id(a))
print ("b", id(b))    # memory location will be different


print (" ")

print ("After Modification:")
a[1] = 20
b[0] = 10
print (a)
print (b)
print ("a", id(a))
print ("b", id(b)) 
    

[1 2 3 4 5 6 7]
[1 2 3 4 5 6 7]
a 2970122563376
b 2970122559696
 
After Modification:
[10 20  3  4  5  6  7]
[10 20  3  4  5  6  7]
a 2970122563376
b 2970122559696


## copy() Method
#### This method is used to create a copy of an existing array. 
#### If the new array get modified. the esisting will not be affected or vice versa. Both arrays are independing in copy () method.

    Ex:
    a = array([1,2,3,4,5,6,7])
    b = copy (a)                    # data will be not same after modication
                                    # data will also be not share
   

In [148]:
from numpy import*
a = array([1,2,3,4,5,6,7])
b = copy (a)
print (a)
print (b)
print ("a", id(a))
print ("b", id(b)) 

print (" ")

print ("After Modification:")
a[1] = 20
b[0] = 10
print (a)
print (b)
print ("a", id(a))
print ("b", id(b)) 

[1 2 3 4 5 6 7]
[1 2 3 4 5 6 7]
a 2970122529488
b 2970122440096
 
After Modification:
[ 1 20  3  4  5  6  7]
[10  2  3  4  5  6  7]
a 2970122529488
b 2970122440096


# Input From User in Numpy 1D Array

In [1]:
from numpy import*

user_input = int(input ("Enter Number of Elements: "))
a = zeros(user_input, dtype=int)
a[0] = 10
a[1] = 20
a[2] = 30   
print (a)     # first three indexed element will be displayed whihc is ginven in a indexs

Enter Number of Elements: 15
[10 20 30  0  0  0  0  0  0  0  0  0  0  0  0]


### Using for-loop

In [ ]:

from numpy import*

user_input = int(input ("Enter Number of Elements: "))
a = zeros(user_input, dtype=int)

# use for-loo for taking input from user 
for i in range(len(a)):      # you can also write 'for i in range (user_input)' there will be no different in thses two terms
    x = int(input("Enter Elements: "))
    a[i] = x

print (a)
    

In [ ]:
from numpy import*

user_input = int(input ("Enter Number of Elements: "))
a = zeros(user_input, dtype=int)

# use for-loo for taking input from user 
for i in range(len(a)):      # you can also write 'for i in range (user_input)' there will be no different in thses two terms
    x = int(input("Enter Elements: "))
    a[i] = x

for i in range (len(a)):
    print (a[1])
    

### Using while-loop

In [2]:
from numpy import*

user_input = int(input ("Enter Number of Elements: "))
a = zeros(user_input, dtype=int)                # by-default dtype is flaot

u = len(a)

i=0
while i<u:
    x = int(input("Enter Elements: "))
    a[i] = x
    i+=1
    
print (a)

Enter Number of Elements: 3
Enter Elements: 15
Enter Elements: 12
Enter Elements: 15
[15 12 15]


In [ ]:
from numpy import*

user_input = int(input ("Enter Number of Elements: "))
a = zeros(user_input, dtype=int)                # by-default dtype is flaot

u = len(a)

i=0
j=0
while i<u:
    x = int(input("Enter Elements: "))
    a[i] = x
    i+=1



# Two Dimentional Array- Multiple Rows, Multiple Colums

## If an array contain more than 1 row and 1 column that is knows as 2D Array. It also known as array of arrays. 



### 2D Array

In [12]:
from numpy import*
a = array ([
            [
               [1,2,3], [4,5,6],
               [7,8,9], [0,1,2]
            ]
          ])
print (a)

[[[1 2 3]
  [4 5 6]
  [7 8 9]
  [0 1 2]]]


### 3D Array

In [10]:
from numpy import*
a = array ([ 
            [1,2,3,4,5],
            [6,7,8,9,10]  
          ])
print (a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [31]:
# we can also write in a single line:
from numpy import*
two_d = array ([ [1,2,3,4,5], [6,7,8,9,10] ])
three_d = array ([ [[1,2,3], [4,5,6], [7,8,9] ] ])

print (two_d)
print ("")
print (three_d)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


### Way of creating Multi-D Array
#### We can use some functions that will help to create a multi-dimentional array
#### Function Names:
#### 1. array () Function
#### 2. zeros () Function
#### 3. ones () Function
#### 4. reshape () Function
#### There are also other function which can be use to create a multi-D array but these are more common. 

### Array Function
#### array () function of numpy is used to create a multi dimentional array.

#### Syntax:
    numpy.array(object, dtype=None, copy=True, order='K', subok=False, ndmin=0)
    
    array_name = numpy.array ([ [elements],elements] ])

In [4]:
# How to creat a multi dimentional array using array fucntion
import numpy
two_d = numpy.array ([ [1,2,3,4,5], [6,7,8,9,10] ])
print (two_d)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [5]:
# How to creat a multi dimentional array using array fucntion
from numpy import*
two_d = array ([ [1,2,3,4,5], [6,7,8,9,10] ])
print (two_d)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


### Accessing 2D Array Elements

In [10]:
from numpy import*
a = array ([ [1,2,3,4,5], [6,7,8,9,10] ])
print (a[0][0])
print (a[0][1])
print (a[0][2])
print (a[0][3])
print (a[0][4])

print (" ")

print (a[1][0])
print (a[1][1])
print (a[1][2])
print (a[1][3])
print (a[1][4])


1
2
3
4
5
 
6
7
8
9
10


### Modifying 2D Array Elements

In [13]:
from numpy import*
a = array ([ [1,2,3,4,5], [6,7,8,9,10] ] , dtype=float)
a[0][0] = 50
print (a[0][0])
print (a.dtype)

50.0
float64


### Sting in an 2D Array

In [17]:
from numpy import*
a = array ([ ['Nasir', 'Yasir', 'Adil'], ['Ali', 'Hashim', 'Raza'] ] )
print (a)

[['Nasir' 'Yasir' 'Adil']
 ['Ali' 'Hashim' 'Raza']]


### We can also assign a name to numpy 

In [18]:
import numpy as np
a = np.array ([ ['Nasir', 'Yasir', 'Adil'], ['Ali', 'Hashim', 'Raza'] ] )
print (a)

[['Nasir' 'Yasir' 'Adil']
 ['Ali' 'Hashim' 'Raza']]


### Accessing 2D Arary using for-loop

In [1]:
from numpy import*
# whithout index number
a = array ([ [1,2,3,4,5], [6,7,8,9,10] ])
# you need to use nested loop in 2D array or more than 1D array
# The outer for-loop represents the rows and the inner for-loop represents the columns in each row.

for r in a:         # r is row 
    for c in r:     # c ic column
        print(c)
    print()

1
2
3
4
5

6
7
8
9
10



In [6]:
from numpy import*
# whith index number
a = array ([ [1,2,3,4,5], [6,7,8,9,10] ])
# you need to use nested loop in 2D array or more than 1D array
# The outer for-loop represents the rows and the inner for-loop represents the columns in each row.

n= len (a) 
print("length of array is",n)  # number of rows

for i in range(n):         # r is row 
    for j in range(len(a[i])):     # c ic column
        print(a[i][j])
    print()

length of array is 2
1
2
3
4
5

6
7
8
9
10



### Accessing 2D Arary using while-loop

In [10]:
  from numpy import*
# whithout index number
a = array ([ [1,2,3,4,5], [6,7,8,9,10] ])
# you need to use nested loop in 2D array or more than 1D array
n = len (a)
print ("number of rows lenght is",n)
i = 0
while i<n:
    j=0
    while j<len(a[i]):
        print (a[i][j])
        j+=1
    i+=1
    print ()


number of rows lenght is 2
1
2
3
4
5

6
7
8
9
10



### Zeros () Fucntion in 2D
zeros () fucntion is use to create arrays with all zeros elements
#### Syntax:
    numpy.zeros(shape, dtype= int, order= 'C')
    where, 
    shape - shape of new array. It can be an int which will represent the number of elements or can be tuple of int. ex:(3,2) 3-rows , 2-columns
    

In [11]:
from numpy import*
a = zeros ((3,2)) 
print (a)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [12]:
#accessing 2D array elemeents
from numpy import*
a = zeros ((3,2)) 
print (a[0][0])

0.0


In [18]:
# accessing 2D array using for-loop without index number
from numpy import*
a = zeros ((3,2), dtype=int)

for r in a:
    for c in r:
        print (c)
    print ()
    
# accessing 2D array using for-loop with index number
from numpy import*
a = zeros ((3,2), dtype=int)
n = len (a)

for i in range (n):
    for j in range(len(a[i])):
        print ("index", i,j, "=", a [i][j])
    print ()

0
0

0
0

0
0

index 0 0 = 0
index 0 1 = 0

index 1 0 = 0
index 1 1 = 0

index 2 0 = 0
index 2 1 = 0



In [20]:
# accessing 2D array using while-loop 
from numpy import*
a = zeros ((3,2), dtype=int)
n = len (a)
i =0
while i<n:
    j=0
    while j<len(a[i]):
        print ("index", i, j, "=", a [i][j])
        j+=1
    i+=1
    print ()

index 0 0 = 0
index 0 1 = 0

index 1 0 = 0
index 1 1 = 0

index 2 0 = 0
index 2 1 = 0



In [21]:
from numpy import*
a = ones ((3,2)) 
print (a) 
# same process as we did in zeros () function

[[1. 1.]
 [1. 1.]
 [1. 1.]]


### Reshape () Function
#### This function is used to change the shape of an array. We can convert 1D array to 2D or 3D array and vice versa. But the the new array should have the same number of elements as in the orginal array. 

#### Syntax:
    reshape (array_name, (n,r,c))
    where,
    array_name - it represent the name of array whose elements to be converted
    n - n is the number of array
    r - r is the number of rows
    c - c is the number of cloumns
    

### Convert 1D Array to 2D & 3D Array

In [22]:
#convert 1D array into 2D
from numpy import*
a = array ([1,2,3,4,5,6])
b = reshape (a, (2,3))
print (a)
print (b)

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


In [23]:
#convert 1D array into 3D
from numpy import*
a = array ([1,2,3,4,5,6,7,8,9,10,11,12])
b = reshape (a, (2,3,2))
print (a)
print (b)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [26]:
#convert 2D array into 1D
from numpy import*
e = array ([ [1,2,3], [4,5,6] ])
f = reshape (e, (6))
print (e)
print (f)

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


#### Flatten Method

In [28]:
# we can also convert 2D or 3D array into 1D array using Flatten Method
from numpy import*
e = array ([ [1,2,3], [4,5,6] ])
f =  e.flatten()
print (f)

[1 2 3 4 5 6]


### How to take input from user in 2D array using for-loop

In [33]:
from numpy import*
m = int(input("Enter Number of Rows: "))
n = int(input("Enter Number of Columns: "))
a = zeros ((m,n), dtype=int)
print (a)

Enter Number of Rows: 10
Enter Number of Columns: 20
[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]


In [35]:
from numpy import*
m = int(input("Enter Number of Rows: "))
n = int(input("Enter Number of Columns: "))
a = zeros ((m,n), dtype=int)

u = len (a)

print (a)
print (u)   # it gives number of row so we can also set m instad of a

Enter Number of Rows: 5
Enter Number of Columns: 2
[[0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]]
5


In [38]:
from numpy import*
m = int(input("Enter Number of Rows: "))
n = int(input("Enter Number of Columns: "))
a = zeros ((m,n), dtype=int)

u = len (a)
print (a)

for i in range(u):
    for j in range(len(a[i])):
        x = int(input("Enter Elements:"))
        a[i][j]= x

# output with index
for i in range (u):
    for j in range (len(a[i])):
        print (a[i][j])
print (a)

Enter Number of Rows: 2
Enter Number of Columns: 2
[[0 0]
 [0 0]]
Enter Elements:15
Enter Elements:12
Enter Elements:15
Enter Elements:13
15
12
15
13
[[15 12]
 [15 13]]


In [39]:
from numpy import*
m = int(input("Enter Number of Rows: "))
n = int(input("Enter Number of Columns: "))
a = zeros ((m,n), dtype=int)

u = len (a)
print (a)

for i in range(u):
    for j in range(len(a[i])):
        x = int(input("Enter Elements:"))
        a[i][j]= x

# output without index
for r in a:
    for c in r:
        print (c)
print (a)

Enter Number of Rows: 2
Enter Number of Columns: 2
[[0 0]
 [0 0]]
Enter Elements:15
Enter Elements:21
Enter Elements:15
Enter Elements:13
15
21
15
13
[[15 21]
 [15 13]]


### How to take input from user in 2D array using while-loop

In [1]:
from numpy import*
m = int(input("Enter Number of Rows: "))
n = int(input("Enter Number of Columns: "))
a = zeros ((m,n), dtype=int)


u = len (a)
i = 0
while i<u:
    j=0
    while j < len (a[i]):
        x = int(input("Enter Element: "))
        a[i][j] = x
        j+=1
    i+=1

i = 0    
while i<u:
    j = 0
    while j < len(a[i]):
        print ("index", i, j, "=", a[i][j])
        j+=1
    i+=1
print (a)  

Enter Number of Rows: 2
Enter Number of Columns: 2
Enter Element: 15
Enter Element: 12
Enter Element: 15
Enter Element: 13
index 0 0 = 15
index 0 1 = 12
index 1 0 = 15
index 1 1 = 13
[[15 12]
 [15 13]]


### Slicing on 2D Array
#### slicing on array can be used to retrieve a piece of the array that contains a group of elemets. It is useful to retreive a range of elements. 
#### Syntax:-
    new_array_name = array_name [start:stop:stepsize:start:stop:stepsize]
    The default start value is 0. The defaul stepsize is 1.

In [6]:
from numpy import*
n = array ([[10, 20, 30],
            [40, 50, 60],
            [70, 80, 90]])
print ("Orignal Array")
print (n)

print (" ")

print (n[0])
print (n[1])
print (n[2])

Orignal Array
[[10 20 30]
 [40 50 60]
 [70 80 90]]
 
[10 20 30]
[40 50 60]
[70 80 90]


In [10]:
from numpy import*
n = array ([[10, 20, 30],
            [40, 50, 60],
            [70, 80, 90]])
print ("Orignal Array")
print (n)

print (" ")

print ("0th Row All Columns")
a = n[0, :]
print (a)

print ("1th Row All Columns")
a = n[1, :]
print (a)

print ("2th Row All Columns")
a = n[2, :]
print (a)

Orignal Array
[[10 20 30]
 [40 50 60]
 [70 80 90]]
 
0th Row All Columns
[10 20 30]
1th Row All Columns
[40 50 60]
2th Row All Columns
[70 80 90]


In [11]:
from numpy import*
n = array ([[10, 20, 30],
            [40, 50, 60],
            [70, 80, 90]])
print ("Orignal Array")
print (n)

print (" ")
print ("0th Column All Rows")
a = n[:, 0]
print (a)


Orignal Array
[[10 20 30]
 [40 50 60]
 [70 80 90]]
 
0th Column All Rows
[10 40 70]


In [13]:
#using for-loop
from numpy import*
n = array ([[10, 20, 30],
            [40, 50, 60],
            [70, 80, 90]])
print ("Orignal Array")
print (n)

print (" ")
print ("0th Column All Rows")
a = n[:, 0]
for i in a:
    print (i)

print ("1th Column All Rows")
a = n[:, 1]
for i in a:
    print (i)
    
print ("2th Column All Rows")
a = n[:, 2]
for i in a:
    print (i)

Orignal Array
[[10 20 30]
 [40 50 60]
 [70 80 90]]
 
0th Column All Rows
10
40
70
1th Column All Rows
20
50
80
2th Column All Rows
30
60
90


In [3]:
#using for-loop
from numpy import*
n = array ([[10, 20, 30],
            [40, 50, 60],
            [70, 80, 90]])
print ("Orignal Array")
print (n)

print (" ")
print ("How to access specific element from an array.")
a = n[:, 2]
print (a)


Orignal Array
[[10 20 30]
 [40 50 60]
 [70 80 90]]
 
How to access specific element from an array.
[30 60 90]


In [6]:
#using for-loop
from numpy import*
n = array ([[10, 20, 30],
            [40, 50, 60],
            [70, 80, 90]])
print ("Orignal Array")
print (n)

print (" ")
print ("How to access specific element from an array.")
a = n[2:3, 2:3]
print (a)


Orignal Array
[[10 20 30]
 [40 50 60]
 [70 80 90]]
 
How to access specific element from an array.
[[90]]


In [7]:
#using for-loop
from numpy import*
n = array ([[10, 20, 30],
            [40, 50, 60],
            [70, 80, 90]])
print ("Orignal Array")
print (n)

print (" ")
print ("How to access specific element from an array.")
a = n[0:2, 1:]
print (a)


Orignal Array
[[10 20 30]
 [40 50 60]
 [70 80 90]]
 
How to access specific element from an array.
[[20 30]
 [50 60]]


### Attributes of Numpy Array
#### ndim - This attribute represents the number of dimentions or axes of the array. The number of dimensions is also reffered as Rank. 
#### Syntax:
            array_name.ndim

### shape - This attribute represents the shape of an array. The shape is a tuple listing the number of elements along each dimension.
#### Syntax:
            array_name.shape
            
### size - This attribute represents the total number of elements in the array. 
#### Syntax:
            array_name.size

### itemsize - This attribute represents the memory size of the array element in bytes.
#### Syntax:
            array_name.itemsize
            
### D-Type: This attribute represents the datatype of elements in the array. 
#### Syntax:
            array_name.dtype

### nbytes: This attribute represents the total number of bytes occupied by an array.
            Total number of bytes = size of array * itemsize of each element in the array. 
#### Syntax:
            array_name.nbytes


In [10]:
from numpy import *
a = array([1,2,3,4,5])
b = array([[10,20,30,40], [50,60,70,80]])
print ()

print (" ")

# ndim Attribute
print ("1D Array ndim:",a.ndim)
print ("2D Array ndim:",b.ndim)

print (" ")

#shape Attribute
#For 1D array shape elements in the row
#For 2D array shape specifies number of row and column in each row
print ("1D Array shape:",a.shape)
print ("2D Array shape:",b.shape)

print (" ")

#size Attribute
print ("1D Array size:",a.size)
print ("2D Array size:",b.size)

print (" ")

#itmesize Attribute
print ("1D Array itemsize:",a.itemsize)
print ("2D Array itemsize:",b.itemsize)

print (" ")

#dtype Attribute
print ("1D Array dtype:",a.dtype)
print ("2D Array dtype:",b.dtype)

print (" ")

#nbytes Attribute
print ("1D Array nbytes:",a.nbytes)
print ("2D Array nbytes:",b.nbytes)


 
1D Array ndim: 1
2D Array ndim: 2
 
1D Array shape: (5,)
2D Array shape: (2, 4)
 
1D Array size: 5
2D Array size: 8
 
1D Array itemsize: 4
2D Array itemsize: 4
 
1D Array dtype: int32
2D Array dtype: int32
 
1D Array nbytes: 20
2D Array nbytes: 32
